server:
  port: 8080
  tomcat:
    max-connections: ${TOMCAT_MAX_CONNECTIONS:20000}
    threads:
      max: ${TOMCAT_MAX_THREADS:5000}
      min-spare: ${TOMCAT_MIN_SPARE:50}
    accept-count: ${TOMCAT_ACCEPT_COUNT:2000}
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:5000}
    keep-alive-timeout: ${TOMCAT_KEEP_ALIVE_TIMEOUT:30000}
spring:
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS:false}
bff:
  http-client: ${HTTP_CLIENT:jdk}
